/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/f0LSlp6Ufyt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function job_opening() {
  return (<>
    <header className="bg-gray-900 text-white py-6 px-4 md:px-6">
      <div className="container mx-auto flex items-center justify-between">
        <div className="flex items-center">
          <img
            alt="Company Logo"
            className="mr-4"
            height={40}
            src="/placeholder.svg"
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width={40} />
          <div>
            <h1 className="text-2xl font-bold">Frontend Developer</h1>
            <p className="text-gray-400">San Francisco, CA</p>
          </div>
        </div>
      </div>
    </header>
    <main className="container mx-auto py-12 px-4 md:px-6">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="col-span-2">
          <h2 className="text-3xl font-bold mb-4">Job Description</h2>
          <div className="space-y-4">
            <div>
              <h3 className="text-xl font-bold mb-2">Responsibilities</h3>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400">
                <li>Develop and maintain responsive, high-performance web applications</li>
                <li>Collaborate with designers and backend developers to create seamless user experiences</li>
                <li>Optimize web applications for speed and scalability</li>
                <li>Write clean, maintainable, and well-documented code</li>
              </ul>
            </div>
            <div>
              <h3 className="text-xl font-bold mb-2">Requirements</h3>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400">
                <li>3+ years of experience in frontend web development</li>
                <li>Proficient in HTML, CSS, and JavaScript</li>
                <li>Experience with modern JavaScript frameworks and libraries (e.g., React, Vue, Angular)</li>
                <li>Familiarity with responsive design and cross-browser compatibility</li>
                <li>Strong problem-solving and critical thinking skills</li>
              </ul>
            </div>
            <div>
              <h3 className="text-xl font-bold mb-2">Benefits</h3>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400">
                <li>Competitive salary and equity options</li>
                <li>Comprehensive health, dental, and vision insurance</li>
                <li>401(k) retirement plan with employer matching</li>
                <li>Generous paid time off and holidays</li>
                <li>Professional development opportunities and training</li>
              </ul>
            </div>
          </div>
        </div>
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6">
          <h2 className="text-2xl font-bold mb-4">Apply Now</h2>
          <form className="space-y-4">
            <div>
              <Label htmlFor="name">Name</Label>
              <Input id="name" placeholder="Enter your name" required type="text" />
            </div>
            <div>
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="Enter your email" required type="email" />
            </div>
            <div>
              <Label htmlFor="resume">Resume</Label>
              <Input id="resume" required type="file" />
            </div>
            <Button className="w-full" type="submit">
              Submit Application
            </Button>
          </form>
        </div>
      </div>
    </main>
  </>);
}
