/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7BUcXxuCMKF
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import {
  DropdownMenuTrigger,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { NotificationImportant } from "@mui/icons-material";

export function Notifications() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-gray-100 font-sans ">
      <header className="flex items-center h-16 px-4  shrink-0 bg-white md:px-6">
        <Link
          className="flex  items-center gap-2 text-lg font-semibold text-gray-900  sm:text-base font-sans"
          href="#"
        >
          <NotificationImportant className="w-6 h-6" />
          <span>Notifications</span>
        </Link>
        <div className="flex items-center w-full gap-4 ml-auto md:gap-2 lg:gap-4">
          <form className="flex-1 ml-auto sm:flex-initial">
            <div className="relative">
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500" />
              <Input
                className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]"
                placeholder="Search applications..."
                type="search"
              />
            </div>
          </form>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Avatar className="h-9 w-9">
                <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
                <AvatarFallback>JP</AvatarFallback>
                <span className="sr-only">Toggle user menu</span>
              </Avatar>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem>My Profile</DropdownMenuItem>
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1 grid grid-cols-1 gap-4 p-4 md:grid-cols-2 lg:grid-cols-3 lg:p-8">
        <Card className="col-span-1 lg:col-span-2">
          <CardHeader className="flex items-center justify-between pb-2">
            <CardTitle className="text-lg font-medium">
              Upcoming Deadlines
            </CardTitle>
            <Link
              className="text-sm font-medium text-blue-500 hover:underline"
              href="#"
            >
              View All
            </Link>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
              <div className="bg-white rounded-lg shadow-sm p-4 ">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Amazon</div>
                  <Badge variant="secondary">2 days</Badge>
                </div>
                <div className="text-sm text-gray-500  mt-1">
                  Software Engineer
                </div>
                <div className="mt-3">
                  <Button size="sm" variant="outline">
                    Set Reminder
                  </Button>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-sm p-4 ">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Google</div>
                  <Badge variant="secondary">5 days</Badge>
                </div>
                <div className="text-sm text-gray-500 mt-1">
                  Product Manager
                </div>
                <div className="mt-3">
                  <Button size="sm" variant="outline">
                    Set Reminder
                  </Button>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-sm p-4 ">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Microsoft</div>
                  <Badge variant="secondary">7 days</Badge>
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                  Software Engineer Intern
                </div>
                <div className="mt-3">
                  <Button size="sm" variant="outline">
                    Set Reminder
                  </Button>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex items-center justify-between pb-2">
            <CardTitle className="text-lg font-medium">
              Application Status
            </CardTitle>
            <Link
              className="text-sm font-medium text-blue-500 hover:underline"
              href="#"
            >
              View All
            </Link>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 gap-4">
              <div className="bg-white rounded-lg shadow-sm p-4 ">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Amazon</div>
                  <Badge variant="primary">Pending</Badge>
                </div>
                <div className="text-sm text-gray-500  mt-1">
                  Software Engineer
                </div>
                <div className="mt-3">
                  <Button size="sm" variant="outline">
                    Update Status
                  </Button>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-sm p-4 ">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Google</div>
                  <Badge variant="success">Accepted</Badge>
                </div>
                <div className="text-sm text-gray-500 mt-1">
                  Product Manager
                </div>
                <div className="mt-3">
                  <Button size="sm" variant="outline">
                    Update Status
                  </Button>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-sm p-4 ">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Microsoft</div>
                  <Badge variant="danger">Rejected</Badge>
                </div>
                <div className="text-sm text-gray-500  mt-1">
                  Software Engineer Intern
                </div>
                <div className="mt-3">
                  <Button size="sm" variant="outline">
                    Update Status
                  </Button>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex items-center justify-between pb-2">
            <CardTitle className="text-lg font-medium">
              Application Timeline
            </CardTitle>
            <Link
              className="text-sm font-medium text-blue-500 hover:underline"
              href="#"
            >
              View Calendar
            </Link>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 gap-4">
              <div className="bg-white rounded-lg shadow-sm p-4 ">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Amazon</div>
                  <div className="text-sm text-gray-500 ">April 15, 2023</div>
                </div>
                <div className="text-sm text-gray-500  mt-1">
                  Application Deadline
                </div>
                <div className="mt-3">
                  <Button size="sm" variant="outline">
                    Set Reminder
                  </Button>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-sm p-4 ">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Google</div>
                  <div className="text-sm text-gray-500 ">May 1, 2023</div>
                </div>
                <div className="text-sm text-gray-500  mt-1">
                  Interview Scheduled
                </div>
                <div className="mt-3">
                  <Button size="sm" variant="outline">
                    Set Reminder
                  </Button>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-sm p-4 ">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-medium">Microsoft</div>
                  <div className="text-sm text-gray-500">May 15, 2023</div>
                </div>
                <div className="text-sm text-gray-500  mt-1">
                  Final Decision
                </div>
                <div className="mt-3">
                  <Button size="sm" variant="outline">
                    Set Reminder
                  </Button>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}

function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
