/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wXXA5vZNdoS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function table() {
  return (
    (<div
      className="bg-white dark:bg-gray-950 rounded-lg shadow-sm overflow-hidden">
      <div className="overflow-x-auto">
        <table className="w-full table-auto">
          <thead className="bg-gray-100 dark:bg-gray-800">
            <tr>
              <th
                className="px-4 py-3 text-left text-sm font-medium text-gray-700 dark:text-gray-300">Name</th>
              <th
                className="px-4 py-3 text-left text-sm font-medium text-gray-700 dark:text-gray-300">Email</th>
              <th
                className="px-4 py-3 text-left text-sm font-medium text-gray-700 dark:text-gray-300">Role</th>
              <th
                className="px-4 py-3 text-left text-sm font-medium text-gray-700 dark:text-gray-300">Status</th>
              <th
                className="px-4 py-3 text-right text-sm font-medium text-gray-700 dark:text-gray-300">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-gray-200 dark:border-gray-800">
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="John Doe" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="john@example.com" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="admin">
                  <SelectTrigger>
                    <SelectValue>Admin</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="editor">Editor</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="active">
                  <SelectTrigger>
                    <SelectValue>Active</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="inactive">Inactive</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-right text-sm">
                <Button size="sm" variant="outline">
                  Save
                </Button>
                <Button className="ml-2" size="sm" variant="outline">
                  Cancel
                </Button>
              </td>
            </tr>
            <tr className="bg-gray-50 dark:bg-gray-800">
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="Jane Smith" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="jane@example.com" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="editor">
                  <SelectTrigger>
                    <SelectValue>Editor</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="editor">Editor</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="pending">
                  <SelectTrigger>
                    <SelectValue>Pending</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="inactive">Inactive</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-right text-sm">
                <Button size="sm" variant="outline">
                  Save
                </Button>
                <Button className="ml-2" size="sm" variant="outline">
                  Cancel
                </Button>
              </td>
            </tr>
            <tr className="border-b border-gray-200 dark:border-gray-800">
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="Bob Johnson" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="bob@example.com" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="user">
                  <SelectTrigger>
                    <SelectValue>User</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="editor">Editor</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="inactive">
                  <SelectTrigger>
                    <SelectValue>Inactive</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="inactive">Inactive</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-right text-sm">
                <Button size="sm" variant="outline">
                  Save
                </Button>
                <Button className="ml-2" size="sm" variant="outline">
                  Cancel
                </Button>
              </td>
            </tr>
            <tr className="border-b border-gray-200 dark:border-gray-800">
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="Alice Williams" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="alice@example.com" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="editor">
                  <SelectTrigger>
                    <SelectValue>Editor</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="editor">Editor</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="active">
                  <SelectTrigger>
                    <SelectValue>Active</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="inactive">Inactive</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-right text-sm">
                <Button size="sm" variant="outline">
                  Save
                </Button>
                <Button className="ml-2" size="sm" variant="outline">
                  Cancel
                </Button>
              </td>
            </tr>
            <tr className="bg-gray-50 dark:bg-gray-800">
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="Michael Brown" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="michael@example.com" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="user">
                  <SelectTrigger>
                    <SelectValue>User</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="editor">Editor</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="pending">
                  <SelectTrigger>
                    <SelectValue>Pending</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="inactive">Inactive</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-right text-sm">
                <Button size="sm" variant="outline">
                  Save
                </Button>
                <Button className="ml-2" size="sm" variant="outline">
                  Cancel
                </Button>
              </td>
            </tr>
            <tr className="border-b border-gray-200 dark:border-gray-800">
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="Sarah Davis" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="sarah@example.com" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="admin">
                  <SelectTrigger>
                    <SelectValue>Admin</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="editor">Editor</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="active">
                  <SelectTrigger>
                    <SelectValue>Active</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="inactive">Inactive</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-right text-sm">
                <Button size="sm" variant="outline">
                  Save
                </Button>
                <Button className="ml-2" size="sm" variant="outline">
                  Cancel
                </Button>
              </td>
            </tr>
            <tr className="bg-gray-50 dark:bg-gray-800">
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="David Lee" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="david@example.com" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="editor">
                  <SelectTrigger>
                    <SelectValue>Editor</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="editor">Editor</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="active">
                  <SelectTrigger>
                    <SelectValue>Active</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="inactive">Inactive</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-right text-sm">
                <Button size="sm" variant="outline">
                  Save
                </Button>
                <Button className="ml-2" size="sm" variant="outline">
                  Cancel
                </Button>
              </td>
            </tr>
            <tr className="border-b border-gray-200 dark:border-gray-800">
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="Emily Chen" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="emily@example.com" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="user">
                  <SelectTrigger>
                    <SelectValue>User</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="editor">Editor</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="inactive">
                  <SelectTrigger>
                    <SelectValue>Inactive</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="inactive">Inactive</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-right text-sm">
                <Button size="sm" variant="outline">
                  Save
                </Button>
                <Button className="ml-2" size="sm" variant="outline">
                  Cancel
                </Button>
              </td>
            </tr>
            <tr className="bg-gray-50 dark:bg-gray-800">
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="Jessica Gonzalez" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="jessica@example.com" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="admin">
                  <SelectTrigger>
                    <SelectValue>Admin</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="editor">Editor</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-sm">
                <Select defaultValue="pending">
                  <SelectTrigger>
                    <SelectValue>Pending</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="pending">Pending</SelectItem>
                    <SelectItem value="inactive">Inactive</SelectItem>
                  </SelectContent>
                </Select>
              </td>
              <td className="px-4 py-3 text-right text-sm">
                <Button size="sm" variant="outline">
                  Save
                </Button>
                <Button className="ml-2" size="sm" variant="outline">
                  Cancel
                </Button>
              </td>
            </tr>
            <tr className="border-b border-gray-200 dark:border-gray-800">
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="Christopher Nguyen" />
              </td>
              <td className="px-4 py-3 text-sm">
                <Input defaultValue="christopher@example.com" />
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>)
  );
}
